/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"16 16 138 2",
"   c #89807D",
".  c #3736BB",
"X  c #2827DD",
"o  c blue",
"O  c #2221E1",
"+  c #2023E9",
"@  c #4E50D5",
"#  c #5254D2",
"$  c #7574C7",
"%  c #7473CA",
"&  c #868582",
"*  c #908F8B",
"=  c #949393",
"-  c #959491",
";  c #969490",
":  c #969491",
">  c #979592",
",  c #9A9895",
"<  c #9A9995",
"1  c #9B9995",
"2  c #9B9996",
"3  c #999A96",
"4  c #A09F88",
"5  c #A09F9B",
"6  c #B79E9B",
"7  c #B8A19D",
"8  c #B9A29E",
"9  c #B9A29F",
"0  c #BAA39F",
"q  c #A8A5A2",
"w  c #AAA8A4",
"e  c #ACABA7",
"r  c #ADABA7",
"t  c #A9ACA8",
"y  c #AAACA8",
"u  c #AAADA9",
"i  c #AEADA9",
"p  c #AFADA9",
"a  c #BBA4A0",
"s  c #BBA4A1",
"d  c #BCA5A2",
"f  c #BCA6A2",
"g  c #BDA6A2",
"h  c #BFA8A5",
"j  c #B0AEAA",
"k  c #B4B5B1",
"l  c #BFBDB9",
"z  c #C4B7AD",
"x  c #C2B5B1",
"c  c #C3B6B2",
"v  c #C4B7B3",
"b  c #C6B9B1",
"n  c #C7BAB2",
"m  c #C6B9B5",
"M  c #C1BFBA",
"N  c #C1BFBB",
"B  c #C8BDB9",
"V  c #CABDB8",
"C  c #CBBFBA",
"Z  c #CBBFBB",
"A  c #CCBFBA",
"S  c #C5C3BE",
"D  c #CDC0BB",
"F  c #CFC1BD",
"G  c #C7C5C1",
"H  c #C6C4C2",
"J  c #CFC5C0",
"K  c #CAC8C3",
"L  c #CDCCC7",
"P  c #CCCDC9",
"I  c #CECCC8",
"U  c #D1C7C3",
"Y  c #D0CECA",
"T  c #D1CFCA",
"R  c #D0CECE",
"E  c #D8D6C1",
"W  c #D2D0CB",
"Q  c #D3D0CC",
"!  c #D0D2CD",
"~  c #D2D0CE",
"^  c #D0D2CE",
"/  c #D5D3CE",
"(  c #D4D3CF",
")  c #D3D4CF",
"_  c #D6D4CF",
"`  c #D8D4CF",
"'  c #DAD8CB",
"]  c #DCDAC9",
"[  c #DEDECE",
"{  c #D2D2D0",
"}  c #D3D5D0",
"|  c #D3D6D1",
" . c #D4D5D0",
".. c #D5D5D0",
"X. c #D6D7D2",
"o. c #D8D6D1",
"O. c #D9D7D2",
"+. c #D9D7D3",
"@. c #DAD7D2",
"#. c #D9D7D7",
"$. c #D6D8D4",
"%. c #D7D9D4",
"&. c #DAD8D3",
"*. c #DBD8D3",
"=. c #D9D9D4",
"-. c #DBD9D4",
";. c #DAD8D5",
":. c #DBDAD5",
">. c #DAD9D7",
",. c #D9DBD6",
"<. c #DCD9D4",
"1. c #DCDAD5",
"2. c #DDDAD5",
"3. c #DDDBD6",
"4. c #DEDBD6",
"5. c #DBDCD7",
"6. c #DDDCD7",
"7. c #DEDCD6",
"8. c #DEDCD7",
"9. c #DFDDD8",
"0. c #E1DFCD",
"q. c #E0DDD8",
"w. c #E0DED8",
"e. c #E0DED9",
"r. c #DEE1DC",
"t. c #E4E1CB",
"y. c #E3E1D3",
"u. c #E7E7D6",
"i. c #E3E1DC",
"p. c #E6E3DE",
"a. c #E7E4DF",
"s. c #E4E5E0",
"d. c #E4E6E1",
"f. c #E5E6E1",
"g. c #E5E7E1",
"h. c #E9E7E2",
"j. c #E6E8E3",
"k. c #E6E9E3",
/* pixels */
"1.1.1.1.&.1.w._ w.-.<.w._ 9.1.1.",
"1.1.1.-.1.6.l 5 G 6.6.S 5 M 6.-.",
"1.1.-.-.&.-.q 2 j 6.1.e 2 w 1.1.",
"1.-.-.-.6.k.! u 5.p.d.%.y } g.1.",
"-.-.@.9.U 6 0 8 s 7 8 0 8 0 d ` ",
"-.9.1.g.7 s B   F c c D   m D &.",
"9.M q ! s J r.2 g.X.P _ k ) _ &.",
"..5 2 u d V -.- 9.Q 6.p.p.-.-.-.",
"r.G j ,.0 D 7.3 i.W p j M 9.-.-.",
"<.6.5.a.0 c ) 3 &.K e p & 1.-.-.",
"&.6.6.a.7 c [ F ' P 1.h.2 O.1.1.",
"w.S e X.d n @ O % 0.G Y * L Y -.",
"_ 2 1 y x z O o . 4 R 6.- O.&.&.",
"w.S w _ d n @ X $ ] / 6.- O.1.1.",
"5.6.6.a.d Z u.t.0..._ 6.2 O.1.&.",
"7.&.&.5.o.@.>.#.@.;.&.1./ &.1.1."
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"32 32 97 2",
"   c #52514F",
".  c #625C59",
"X  c #5A5973",
"o  c #6D6C6A",
"O  c #706866",
"+  c #70726F",
"@  c #777673",
"#  c #7A7976",
"$  c #7D7C79",
"%  c #8D5654",
"&  c #8C5957",
"*  c #8D5A58",
"=  c #915E5C",
"-  c #93615F",
";  c #847B78",
":  c #82817D",
">  c #6A6982",
",  c #5050AD",
"<  c #5857B6",
"1  c #5251B8",
"2  c #5857B9",
"3  c #6362AD",
"4  c #6E6DA8",
"5  c #7D7BAA",
"6  c #6463B5",
"7  c #6A69B5",
"8  c #2626C5",
"9  c #2929C5",
"0  c #0000EB",
"q  c #0000F1",
"w  c #0202FE",
"e  c #858481",
"r  c #888683",
"t  c #8A8986",
"y  c #8E8C89",
"u  c #918E8B",
"i  c #93918E",
"p  c #959491",
"a  c #989693",
"s  c #9B9995",
"d  c #9E9D99",
"f  c #B2928F",
"g  c #A09F9B",
"h  c #B29A96",
"j  c #A2A19D",
"k  c #A6A4A1",
"l  c #A8A7A3",
"z  c #ACAAA6",
"x  c #AEADA9",
"c  c #B7AAA6",
"v  c #B0AEAA",
"b  c #BAADA9",
"n  c #B3B2AE",
"m  c #A7A6BE",
"M  c #A9A7BF",
"N  c #B6B5B1",
"B  c #B9B7B3",
"V  c #B3B1B8",
"C  c #B8B6BB",
"Z  c #BFBDB8",
"A  c #C3B6B2",
"S  c #C6B8B4",
"D  c #C9BBB7",
"F  c #C3BBB9",
"G  c #C5C2BD",
"H  c #CBC0BC",
"J  c #D1C3BE",
"K  c #C7C5C0",
"L  c #C9C7C2",
"P  c #CCCAC5",
"I  c #CECCC8",
"U  c #D4C6C1",
"Y  c #D3CBC6",
"T  c #D0CFCA",
"R  c #D4D2CD",
"E  c #D7D5D0",
"W  c #D9D6D2",
"Q  c #D7D8D3",
"!  c #DCDAD5",
"~  c #DFDDD8",
"^  c #E0DDD7",
"/  c #E1DFD9",
"(  c #E4E5CE",
")  c #E2E3D7",
"_  c #E8E6D7",
"`  c #EDEBD5",
"'  c #E2E1DC",
"]  c #E2E5E0",
"[  c #E8E6E0",
"{  c #E5E9E4",
"}  c #ECEAE4",
"|  c #EBEEE9",
" . c #F0EEE8",
".. c #F3F3EE",
"X. c #FDFAEE",
"o. c #F6F7F1",
"O. c #FEFBF3",
/* pixels */
"! ! ! ! ! ! ! ! ! ! ! ! ! W ~ ! W ! W ~ ~ W ~ W ~ ~ W ~ W ! ! ~ ",
"! ! ! ~ ! ! ! ! ! ! ! ! ! / R W ~ ! ~ W W ! W ~ W R ^ W ~ W ~ W ",
"! ! ! ! ! ! ! ~ ! ! ! W ' I r s ~ ~ W ~ ! ! / ! i y R ' W ~ ! ! ",
"! ! ! ! ! ! ! ! ! ! ! / P u x j d W ~ W ! ~ R s j x i T ~ W ! ! ",
"! ! ! ! ! ! ! ! ! ! ! ^ i r n x @ n ' W W ' j ; v n : s ' W ! ! ",
"! ! ~ ! ! ! ! ~ ! ! ! W ' d n j B ' W ~ ~ W ' v k v k ' W ! ! ! ",
"! ! ! ! ! ! ! ! ! ! ! W / a d y n ' W ! ! ! ' z i a g ' W ! ~ W ",
"! ! ! ! ! ! ! ! ! W ! W ! Z x x Y ! W W W W ! L z x G ^ W W W ~ ",
"! ! ~ ! ! ! ! ! ! ' ] ] ' { | | ] ] ] ] ] ] ' ] | | { ] ] { ! ! ",
"! ! ! ! ! W ! ! ' f % - = = * * = - = - = - - - * * = = * - T ~ ",
"! ! ! ! ! ! ! W ] = h H A U . u H S D c b F A U ; O U A S S E ! ",
"! ! W ~ ^ W ! W ] - H { ! ..+ z | / ' R Q { ' ..s : o.' ] ] ! ! ",
"! W ' L u ' ' ! ] = S / E { o k _ E ~ L F P K R y $ W K L L W ! ",
"! / I i r d i Z { * S ' E } o k { ! ~ P G R R I T T T T T T W ! ",
"~ R r x N n d n | - S ' E } o k [ W ~ P T / ! ~ ! ^ ! / ! ~ ! ! ",
"! W s j x d y v | * S ' E } o j [ W ~ P P ! W W W W ! ! ! ! ! ! ",
"! ! ^ d # N v Y { = S ] E } o k ] W ^ I !  .} } } / ! ! ! ! ! ! ",
"! ! ! Q v [ / ^ ] = S / E } o k [ W / G e y y r y P ~ ! ! ! ! ! ",
"! ! ! ! / ! W W ] = D ] Q  .o l } ~ ' L $ e : u   : } E ! ! ~ ! ",
"! ! ! ! ! ^ ! W ] = c T K ! o d R L I F ~  .[ O.d $ } W ! ! ! ! ",
"! ! ! ! ! ! ! W ] = c E P I P I I I R F P W R ] u $ } W ! W ! ! ",
"! ! ! ! / Q ! W ] - D ] ` ` ` ` ` ' ' I T ' ! } a $ | ! ~ ~ ! ! ",
"! W ^ W k ] ' ~ ] - S ' 4 1 < 2 , V ) K K R I ' y @ ' I T R W ! ",
"! ^ ! p $ x l L { * S ( 9 w w w 0 m X.R Z P K R y @ E K K P W ! ",
"! W i k v k i v | * S ( 8 w w w q + s y R ' ! } a $  .! / ^ ! ! ",
"~ R y z n x a v | = F ) 8 w w w q X : $ I ~ W } i $ } R ! ! ! ! ",
"Q ^ R i : k g F { = S ( 8 w w w q M X.W I ~ W } i $ } W ! ! ! ! ",
"! ! / T s ] / ^ ] - S ' 5 6 7 7 6 C ) G I ~ R } i $ } W ! ! ! ! ",
"! ! W ^ / W ! W ] = S ] _ ` ` ` ` ~ ! P Y ~ E } i $ } W ! ! ! ! ",
"! ! ! ! ! ! ! W ] - S / W Q Q Q E ! / P I ~ E } i $ } W ! ! ! ! ",
"! ! ! ! ! ! ! ! ! Y W ! ! ! ! ! ! ! ! W W ~ W ~ R T ~ ! ! ! ! ! ",
"! ! ! ! ! ! ! ! Q ~ ! ! ! ! ! ! ! ! ! ! ! ! ! W ~ ~ ! ! ! ! ! ~ "
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 118 2",
"   c #3B1414",
".  c #2B2A29",
"X  c #312F2E",
"o  c #30302F",
"O  c #323534",
"+  c #731F1E",
"@  c #4D2423",
"#  c #613433",
"$  c #454443",
"%  c #4E4D4B",
"&  c #504F4D",
"*  c #565640",
"=  c #52514F",
"-  c #555452",
";  c #5A5957",
":  c #5C5E5C",
">  c #7B4B49",
",  c #61605E",
"<  c #696866",
"1  c #6C6B69",
"2  c #7D7C66",
"3  c #72716F",
"4  c #767572",
"5  c #797775",
"6  c #7A7976",
"7  c #7D7C79",
"8  c #814D4C",
"9  c #925E5C",
"0  c #96615F",
"q  c #956260",
"w  c #9C6664",
"e  c #966A67",
"r  c #9A6E6C",
"t  c #9D716F",
"y  c #807F7C",
"u  c #9F7471",
"i  c #9F7875",
"p  c #A27573",
"a  c #A57875",
"s  c #A77B78",
"d  c #81817E",
"f  c #101094",
"g  c #17179A",
"h  c #1010A7",
"j  c #1616B6",
"k  c #1F1EB2",
"l  c #2929A3",
"z  c #2929AC",
"x  c #2121B3",
"c  c #2F2EB0",
"v  c #3030B1",
"b  c #43428E",
"n  c #75749E",
"m  c #7E7D9D",
"M  c #7675A0",
"N  c #0000E1",
"B  c #0101EC",
"V  c #0000F3",
"C  c #0202FE",
"Z  c #858481",
"A  c #888783",
"S  c #8A8985",
"D  c #8D8C89",
"F  c #908F8C",
"G  c #93928E",
"H  c #83829A",
"J  c #979693",
"K  c #989793",
"L  c #9A9996",
"P  c #9E9D9A",
"I  c #A19F9C",
"U  c #A3A19E",
"Y  c #8382A1",
"T  c #9492A0",
"R  c #A6A5A1",
"E  c #A8A6A2",
"W  c #ABAAA6",
"Q  c #AEADA9",
"!  c #B2B1AD",
"~  c #B6B5B1",
"^  c #B9B7B2",
"/  c #BBB9B5",
"(  c #B7BFBA",
")  c #C0BEBA",
"_  c #C3C1BD",
"`  c #CCC5C1",
"'  c #C2CBC6",
"]  c #CCCAC6",
"[  c #CFCDC9",
"{  c #D2CFCA",
"}  c #DCD9C1",
"|  c #D5D2CD",
" . c #D8D3CE",
".. c #DBD9CA",
"X. c #D7D5D1",
"o. c #D9D6D1",
"O. c #DCDAD5",
"+. c #DEDCD8",
"@. c #E0DECD",
"#. c #E0DCD6",
"$. c #E1DED9",
"%. c #EAE6D6",
"&. c #E4E2DD",
"*. c #E8E5DB",
"=. c #ECE9DC",
"-. c #F5F3DA",
";. c #EAE7E2",
":. c #E3EBE6",
">. c #EEECE6",
",. c #E5EDE8",
"<. c #EEECE9",
"1. c #F0EEE8",
"2. c #E8F1EB",
"3. c #F3F1EC",
"4. c #EDF6F0",
"5. c #EFFFFD",
"6. c #F0F9F3",
"7. c #FBFFFC",
/* pixels */
"O.O.O.+.O.O.O.O.O.O.+.O.O.O.+.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.o.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.+.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.+.o.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.+.O.",
"O.O.O.O.O.O.+.O.O.O.O.O.O.O.O.O.O.O.O.O.O.$.{ $.O.O.O.O.O.O.O.O.O.O.o.$.X.o.+.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.+.O.O.O.O.O.O.O.O.O.o.*.I 1 _ &.O.O.O.O.O.O.O.O.o.&.| 5 A +.+.o.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.+.O.O.O.O.O.O.O.O.O.O.o.o.&.L S ! 5 ( &.o.O.O.O.O.O.o.$.{ 6 U L Z +.+.O.O.O.O.O.O.O.",
"O.O.O.+.O.O.O.O.O.O.O.O.O.O.O.+.O.o.&.U D ~ ! ! y _ $.O.O.O.O.O.+.| Z R ! ^ L D O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.+.O.O.O.O.&.W ; G ! Q W 7 , { O.O.O.O.O.$.4 1 R ! ! P , S &.O.O.O.O.O.O.",
"+.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.o.+.| { d W ~ K L O.| O.O.O.O.O.O.o.! S ~ ! d _ ..O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.+.O.O.O.O.O.O.O.O.+.o.O.&.F Q ^ L R ;.O.O.O.O.O.O.o.&.) D ^ ~ S | $.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.+.O.O.o.+.O.#.A U Q F U &.o.O.O.O.O.O.o.&./ d Q W 7 ] O.O.O.O.O.O.O.O.",
"O.+.O.O.O.O.O.O.#.O.O.O.O.O.O.O.O.O.o.&.L S G d / &.o.O.O.O.O.O.O.#.[ A G D D o.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.o. .o.O. .#.$.$.$.#.o.o.o.o.o.o.o.O. .O.*.#.+.&.o.o.o.o.o.O.O.O.O.",
"O.O.O.O.O.O.O.+.O.O.O.O.O.O.+.:.,.,.2.:.:.:.:.:.:.,.:.:.,.:.,.,.:.:.:.:.:.:.:.:.:.,.,.,.O.O.O.O.",
"O.O.O.+.O.O.O.O.O.O.O.O.O.+.` u r r r r r t s r r r r r r t r r r r r r p p e t r r r t { +.O.O.",
"O.O.O.O.O.O.O.O.+.O.O.O...:.i + e 9 9 9 0 >   0 9 9 9 9 0 8 9 9 9 9 9 w @ # w 9 9 9 0 0 { O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.o.,.r e 5.:.:.:.6.( O 4.,.,.,.,.2.' :.:.,.,.:.7.: d 7.:.:.,.,.,.O.O.O.O.",
"O.O.O.O.O.O.o.&.O.O.O.#.o.,.r 9 :. ... .&.W X $.o.o.o.o.O.^  .o.o. .| >.- 6 >.| |  . .o.O.O.O.O.",
"O.O.O.O.O.O.&.E | O.o.o.o.,.r 9 ,.o.O.o.;.Q . &.o.O.O.O.#./ o.#.+.O.O.2.- 7 3.o.+.+.$.+.O.O.O.O.",
"O.O.O.O.o.&.I , | $.$.$.o.,.r 9 ,.o.O.O.&.Q O &.o.O.O.o.$.! ~ / / / ^ _ 5 S _ ^ / / ^ / X.O.O.O.",
"O.O.O.O.&.L D G d D d P #.,.r 9 ,.o.O.O.&.Q o &.o.O.O.O.+.^ | o.o.o.o.X.&.+.o...o.o.o.o.O.O.O.O.",
"O.O.O.+.P S ~ ! W Q U D #.,.r 9 ,.o.O.o.*.Q X &.O.o.+.O.+./ o.+.O.O.O.+.o.O.O.+.O.+.O.O.O.O.O.+.",
"O.O.O.{ 1 ! ! Q ~ ^ Q F #.,.r 9 ,.o.O.O.;.Q O $.o.O.O.o.+./ o.+.o.O.O.O.O.O.o.O.O.o.O.O.O.O.O.O.",
"O.O.o.&._ 5 ! W J L D S #.:.r 9 ,.o.#.o.&.Q X &.o.O.+.o.+./ o.o.O.O.O.O.O.O.O.+.O.O.O.O.O.O.O.O.",
"O.O.O.o.;./ m 6 J E I / #.,.r 9 ,.o.+.O.;.Q o &.O.O.O.O.+./ | o.o.o.o.o.o.o.O.o.O.O.O.O.O.O.O.O.",
"O.O.O.O.X.&._ , O.;.&.$.o.,.r 9 ,.O.X.O.;.Q o &.o.O.O.O.O.) ,.1.>.>.>.1.,.&.O.O.O.O.O.+.O.+.O.O.",
"O.O.O.O.+.o.%.] X.o.o.o.o.,.r 9 ,.o.+.X.$.Q o $.o.O.O.o.&.G $ = & & & % - ) $.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.o.O.O.O.O.O.o.,.r 9 ,.o.X.X.;.Q o $.O.O.o.o.&.U 5 d y d 7 D . d >. .O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.o.O.O.O.O.o.,.r 9 ,.o.#.O.:.! o ;.O.O.+.O.#._ =.>.>.>.;.7.: 6 <.o.+.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.o.,.r 8 ' / / / ( R , ) / / / / / W o.o.o.o.| >.- 6 >.o.O.O.O.O.O.O.O.O.",
"O.O.O.+.+.o.O.O.O.O.O.O.o.,.r 9 :.o.o.o.| X.&.X.o.o.o.X.o.^ o.O.O.O.o.1.- 6 >...O.O.O.O.O.O.O.O.",
"O.O.O.O.o.O.O.O.#.o.O.#.o.,.r 9 ,.X.O.+.+.+.O.+.+.+.O.O.$./ o.O.O.o.o.>.- 6 ,.o.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.o.+.$.o.o.O.O.o.,.t 9 :.o.o.} } } _ } } @.O.O.+./ O.+.O.+.O.3.- 7 3.O.#.+.+.+.O.o.O.+.",
"O.O.O.O.o.+.| 4 o.&.$.$.| ,.t 9 :.&.H h x k x x x b @.O.#.^ ] { [ [ ] $.- 5 #.] [ { [ [ o.+.o.O.",
"O.O.O.O.&.| d 3 ! ) / ] o.:.r 9 :.%.n V C C C C C z _ %.O.! / ) ) ) / { - 3 { / / / _ ) o.O.O.O.",
"O.O...&.| 7 R R A D y A &.:.r 9 :.%.M V C C C C C v -.3.2.` O.&.$.$.O.3.- 7 3.O.&.$.&.+.O.O.O.O.",
"O.O.O.o.5 R ! ! ^ ^ W F +.:.t 9 :.%.M V C C C C C f * ; % 6 $.X.O.O.| <.- 6 ,.o.O.O.o.O.O.O.O.O.",
"O.o.O.O.S K ~ ! ! ! W G #.:.t 9 :.%.n V C C C C C g 2 7 4 D +.O.O.O.o.1.- 6 >.o.O.O.O.O.O.O.O.O.",
"O.O.O.O.+.Z L P y S 6 D &.:.r 9 :.%.M V C C C C C c -.,.1.` X.+.o.O.o.<.- 6 >.o.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.+.D < _ | ] o.o.:.r 9 :.=.m N B B B B V l ..o.X./ X.X.O.O.o.<.- 6 >.o.O.O.O.O.O.O.+.O.",
"O.O.O.O.O.O.+.S | &.+.+.o.,.t 9 :.+.! m Y Y Y Y m T #.o.O./ o.O.O.O...1.- 6 >.o.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.&.O.o.o.O.o.:.r 9 ,.o.&.=.*.=.;.*.=.*.O.O.+./ o.O.o.O.o.1.- 6 >.o.O.O.+.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.o.:.t 9 ,.o.O.O.O.O.X.X.O.O.O.O.+.^ o.O.O.O.X.2.- 6 >.X.O.O.O.O.+.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.o.:.t 0 :.X.O.O.O.O.O.O.O.O.O.O.#./ o.O.O.O.o.>.; y >.X.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.+.| { O.O.O.O.O.O.O.O.O.O.O.O.O...O.O.O.O.O.O.[ { +.O.O.O.O.+.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.o.+.+.O.O.O.O.+.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.#.#.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.o.o.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.+.O.O.O.O.O.O.+.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.+.O.O.O.O.O.O.O.O.O.O.O.O.#.O.O.O."
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
};
const int n_xpm_icons = 3;
