/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"16 16 116 2",
"   c #3534BD",
".  c #7372BE",
"X  c #3A3AC7",
"o  c #6665C6",
"O  c #6968C6",
"+  c #7170C4",
"@  c #8887BF",
"#  c #A2A1B6",
"$  c #B7B5B1",
"%  c #B7B5B3",
"&  c #BAB8B4",
"*  c #BFBEB4",
"=  c #BAB9B8",
"-  c #C2C0BC",
";  c #C3C1BE",
":  c #C4C3BE",
">  c #C5C3BE",
",  c #C6C4BF",
"<  c #C9C7B9",
"1  c #D5D3BF",
"2  c #8887CE",
"3  c #9E9CC1",
"4  c #A4A2C4",
"5  c #ACABC3",
"6  c #A2A0CD",
"7  c #A9A7C8",
"8  c #B6B4CD",
"9  c #ACABD0",
"0  c #C5C3C0",
"q  c #C7C5C1",
"w  c #C8C6C1",
"e  c #C8C6C2",
"r  c #C9C7C3",
"t  c #C9C7C4",
"y  c #C9C8C3",
"u  c #CAC8C3",
"i  c #CDCBC1",
"p  c #CECCC0",
"a  c #C9C8C4",
"s  c #CAC8C4",
"d  c #CAC9C4",
"f  c #CBC9C5",
"g  c #CCCAC6",
"h  c #CDCBC6",
"j  c #CDCBC7",
"k  c #CFCDC7",
"l  c #C7C6C9",
"z  c #C3C1CF",
"x  c #CECDC8",
"c  c #CECCC9",
"v  c #CFCDC9",
"b  c #CFCDCA",
"n  c #D0CEC2",
"m  c #D0CEC5",
"M  c #D1CFCA",
"N  c #D4D2C5",
"B  c #D9D7C4",
"V  c #D8D6C5",
"C  c #D3D1CB",
"Z  c #D2D0CC",
"A  c #D2D1CC",
"S  c #D3D1CC",
"D  c #D3D1CD",
"F  c #D4D2CD",
"G  c #D5D3CE",
"H  c #D5D3CF",
"J  c #DBD9CA",
"K  c #DCDACF",
"L  c #C9C7D0",
"P  c #D5D3D0",
"I  c #D4D2D3",
"U  c #D6D4D0",
"Y  c #D7D5D1",
"T  c #D8D6D1",
"R  c #D9D7D1",
"E  c #D9D7D2",
"W  c #D8D6D3",
"Q  c #D9D7D3",
"!  c #D9D7D4",
"~  c #D9D7D5",
"^  c #DAD8D3",
"/  c #DFDDD1",
"(  c #DAD8D4",
")  c #DAD9D4",
"_  c #DBD9D4",
"`  c #DAD8D5",
"'  c #DAD9D5",
"]  c #DBD9D5",
"[  c #DAD8D6",
"{  c #DBD9D6",
"}  c #DCDAD4",
"|  c #DCDAD5",
" . c #DDDBD5",
".. c #DCDAD6",
"X. c #DDDBD6",
"o. c #DDDBD7",
"O. c #DEDCD6",
"+. c #DEDCD7",
"@. c #DDDBD8",
"#. c #DFDDD8",
"$. c #E0DED0",
"%. c #E0DED6",
"&. c #E1DFD6",
"*. c #E0DED8",
"=. c #E1DFDA",
"-. c #E2E0D3",
";. c #E3E1D3",
":. c #E7E5D1",
">. c #E6E4D3",
",. c #E3E1D6",
"<. c #E7E5D5",
"1. c #E6E4D6",
"2. c #E6E4D7",
"3. c #E9E7D4",
"4. c #EAE8D4",
"5. c #E7E5D8",
/* pixels */
"| | | | ( ,.:.( ( | | (  .Q ^ | ",
"| | | Q <.6 o >.@.| Q @.F e  .| ",
"| | | ( ,.8 @ i j ( 5.$.: | | | ",
"| | | | | K V #.v p 7 3 / | ^ | ",
"| | ( | | H y *.( V . + 3.~ ( | ",
"| ^ ( |  .^ q v q v <.J 0 #.| | ",
"|  .,.| ^ e $ D | @.~ @.M e | ^ ",
"| I z k y v d *.^ | | |  .M Y | ",
"3.9   < I | d #.| ^ | | (  .| | ",
"~ @.$ : m : & F |  . .| | ( ( | ",
"| | C = ~ | - j e d D ^ #. .| | ",
"| | Y 1 i Q t #.| F j q y D ^ | ",
"| ( ;.O 4 N m | | |  .| F j Q | ",
"( ~ ,.2 5 * # ( | | | ^  .#.| | ",
"| _ ( 3.<.l X L %.^ | | ^ | ^ | ",
"| | | Q ^  .Q _ | | | | | | | | "
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"32 32 213 2",
"   c #76759F",
".  c #4646AE",
"X  c #4A4AB0",
"o  c #6161A9",
"O  c #6E6EA9",
"+  c #7B7AAC",
"@  c #6564BC",
"#  c #7C7BB4",
"$  c #7170BD",
"%  c #7C7BB9",
"&  c #0101D2",
"*  c #0505D5",
"=  c #0B0BD2",
"-  c #0808D9",
";  c #2121C4",
":  c #302FC9",
">  c #0101E4",
",  c #0000E9",
"<  c #0000F2",
"1  c #0000F5",
"2  c #0000F9",
"3  c #4343C7",
"4  c #4847C2",
"5  c #6968C0",
"6  c #8A8995",
"7  c #9D9C90",
"8  c #9A9895",
"9  c #A09F9B",
"0  c #A3A19E",
"q  c #9391A1",
"w  c #9795AA",
"e  c #8583BF",
"r  c #8D8CBE",
"t  c #9695BF",
"y  c #ADACA8",
"u  c #AEACA8",
"i  c #AEADA9",
"p  c #AFADAB",
"a  c #AFAEAA",
"s  c #AEADAC",
"d  c #B0AEAA",
"f  c #B0AEAB",
"g  c #B0AFAB",
"h  c #BDBCA5",
"j  c #B3B1A9",
"k  c #B1B0AC",
"l  c #B2B0AC",
"z  c #B2B1AD",
"x  c #B3B1AD",
"c  c #B3B2AE",
"v  c #B4B2AE",
"b  c #B4B3AF",
"n  c #B5B3AF",
"m  c #B6B5AC",
"M  c #B8B6AC",
"N  c #BBB9AD",
"B  c #A1A0B0",
"V  c #ABA9B7",
"C  c #B5B3B3",
"Z  c #B5B4B0",
"A  c #B6B4B0",
"S  c #B6B5B1",
"D  c #B7B5B1",
"F  c #B7B5B4",
"G  c #B8B6B2",
"H  c #B8B7B2",
"J  c #B9B7B3",
"K  c #B8B7B4",
"L  c #B9B8B3",
"P  c #BCBAB0",
"I  c #BAB8B4",
"U  c #BBB9B5",
"Y  c #BCBAB6",
"T  c #BDBBB7",
"R  c #BDBCB7",
"E  c #BEBCB8",
"W  c #BEBDB8",
"Q  c #BFBDB9",
"!  c #BDBBBD",
"~  c #C0BEB9",
"^  c #C0BEBA",
"/  c #C0BFBA",
"(  c #C1BFBA",
")  c #C1BFBB",
"_  c #C6C4B3",
"`  c #C3C1B7",
"'  c #C7C5B4",
"]  c #C7C5B5",
"[  c #CECCB6",
"{  c #C2C0BB",
"}  c #C2C0BC",
"|  c #C3C1BD",
" . c #C3C1BE",
".. c #C5C3BE",
"X. c #C5C3BF",
"o. c #C6C4BF",
"O. c #C8C6BE",
"+. c #C8C7BE",
"@. c #9998C0",
"#. c #C0BEC0",
"$. c #C5C3C0",
"%. c #C6C4C0",
"&. c #C6C5C0",
"*. c #C7C5C0",
"=. c #C7C5C1",
"-. c #C7C6C1",
";. c #C1C0C5",
":. c #C8C6C1",
">. c #C8C6C2",
",. c #C9C7C2",
"<. c #CBC9C0",
"1. c #C9C8C3",
"2. c #CAC8C3",
"3. c #CDCBC1",
"4. c #CAC8C4",
"5. c #CBC9C4",
"6. c #CCCAC5",
"7. c #CDCBC6",
"8. c #CDCBC8",
"9. c #CFCDC8",
"0. c #CFCDC9",
"q. c #D0CEC8",
"w. c #D0CFC8",
"e. c #D0CEC9",
"r. c #D1CFCA",
"t. c #D6D4C2",
"y. c #D2D0CB",
"u. c #D3D1CC",
"i. c #D2D0CE",
"p. c #D4D2CD",
"a. c #D4D2CE",
"s. c #D5D3CE",
"d. c #D5D3CF",
"f. c #D6D4CF",
"g. c #DFDDCA",
"h. c #DEDCCF",
"j. c #D7D5D0",
"k. c #D7D5D1",
"l. c #D7D6D0",
"z. c #D8D6D1",
"x. c #D9D7D2",
"c. c #D8D6D3",
"v. c #D8D6D4",
"b. c #D9D7D4",
"n. c #D8D6D5",
"m. c #D9D7D5",
"M. c #D9D7D6",
"N. c #DBD9D0",
"B. c #DAD8D3",
"V. c #DBD9D3",
"C. c #DDDBD1",
"Z. c #DAD8D4",
"A. c #DAD9D4",
"S. c #DBD9D4",
"D. c #DAD8D5",
"F. c #DBD9D5",
"G. c #DBDAD5",
"H. c #DBD9D7",
"J. c #DCDAD4",
"K. c #DCDAD5",
"L. c #DDDBD5",
"P. c #DCDAD6",
"I. c #DDDBD6",
"U. c #DCDAD7",
"Y. c #DEDCD6",
"T. c #DEDCD7",
"R. c #DFDDD7",
"E. c #DDDBD8",
"W. c #DCDAD9",
"Q. c #DDDBD9",
"!. c #DFDDD8",
"~. c #DFDDD9",
"^. c #E0DECC",
"/. c #E1DFD0",
"(. c #E0DED7",
"). c #E1DFD7",
"_. c #E0DED8",
"`. c #E0DED9",
"'. c #E1DED9",
"]. c #E1DFD9",
"[. c #E0DEDA",
"{. c #E1DFDA",
"}. c #E1DEDB",
"|. c #E1DFDB",
" X c #E2DFDA",
".X c #E1DFDD",
"XX c #E5E3CE",
"oX c #E7E5CE",
"OX c #E3E1D1",
"+X c #E2E0D3",
"@X c #E6E3D4",
"#X c #E7E5D6",
"$X c #E9E7D3",
"%X c #EAE8D4",
"&X c #EBE8D6",
"*X c #E2E0D8",
"=X c #E3E1D9",
"-X c #E2E0DA",
";X c #E2E0DB",
":X c #E3E1DB",
">X c #E4E2D8",
",X c #E6E4D8",
"<X c #E6E4DA",
"1X c #E7E5DB",
"2X c #E3E1DC",
"3X c #E5E2DD",
"4X c #E5E3DE",
"5X c #E7E4DF",
"6X c #EEEBDB",
"7X c #EFEDDB",
"8X c #F5F2DD",
"9X c #E7E5E0",
"0X c #E9E7E2",
/* pixels */
"K.K.K.K.K.K.K.K.K.S.K.m.S.S.K.S.K.K.K.K.K.K.K.K.K.S.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.K.S.(.OXK.N.K.K.K.K.K.K.K.K.K.S.K.x.s.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.S.(.$.+ f.V.K.K.S.K.K.K.K.K.K.m.-Xb 7.[.V.K.K.",
"K.K.K.K.K.K.K.K.V.m.oX: < # 7XK.m.S.K.S.K.N.K.S..XR T -Xx.K.K.K.",
"K.K.K.K.K.K.K.K.S.m.@X@.; w P 8.[.[.V.V.K.K.x.[.2.b [.x.K.V.K.K.",
"K.K.K.K.K.K.K.K.K.K.K./.h 1Xw.G b 7.[.[.V.x.E.s.d K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.S.K.x.C K.K.[.w.G b 5.[.&XXXd s.K.B.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.S.K.m.Z K.K.x.[.[.u.G N @ X +.[.V.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.S.K.S.Z K.K.K.S.x.[.0Xj * , #.-XV.V.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.S.S.K.Z N.m.K.[.!.,.d ` t + P .Xx.K.V.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.S.S.E.b x.;XK.o.k T f.[.#X6XT T -XV.K.V.K.K.K.",
"K.K.K.K.K.K.K.S.K.N.m.!.T x.o.k T x.[.E.N.m.x..XG R -XK.K.K.K.K.",
"K.K.K.K.K.S.S.S.S.S.;XT.0 u ^ x.[.K.S.S.K.x.K.x.-Xn ) 2Xx.K.V.K.",
"K.S.K.S.m.S.S.S..XS.^ b 9 s.2XK.N.K.K.S.K.K.K.K.K.[.b $.[.K.K.K.",
"K.K.S.K.<X!.[.N.^ k ^ (.T s.S.S.K.S.K.K.K.K.K.K.K.K.[.d w.K.K.K.",
"K.S.K.N.V w.{ d | K.[.[.D s.K.K.K.K.K.K.K.K.K.K.K.V.K.K.x.K.V.K.",
"K.m.&X% 1 . [ .X2XK.x.[.J s.K.K.K.K.K.K.K.K.K.K.K.K.B.K.K.K.K.K.",
"K.m.#X@.& o _ F 7.x.[.2XJ w.K.V.K.S.K.K.K.K.K.K.K.B.K.K.K.K.B.K.",
"K.V.x.,X] 7 s.w.T b J w.J s.;XK.N.V.S.K.B.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.m.E.d d [.[.B.8.) 8 u 7.x..X[.K.m.K.B.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.x.(.T T J [.B.(.5XR ^ { b G ,.x.[.[.V.x.V.K.K.V.K.K.K.K.K.",
"K.K.V.K.(.,.$.T ..[.x.[.T q.2X(.w.E b G +.x.[.[.K.x.K.K.K.K.K.K.",
"K.K.K.K.K.x.b K.u x.V.[.^ ,.(.V.E.[.T.w.^ Z G ,.x.[.[.K.K.K.K.K.",
"K.K.K.K.B.[.G V.s.d (.[.^ ,.[.V.K.x.K.T.[.K.w.^ b b ..s.K.B.K.K.",
"K.K.K.x.K.[.+.q (.^ ~ 0X^ %.[.V.K.S.K.S.B.S.(.[.(.s.^ b s.K.K.K.",
"K.K.K.K.m.$X$ < @ 8Xu s.$.| [.K.S.K.K.K.S.K.B.B.K.K.[.(.B.K.B.K.",
"K.K.K.K.m.,Xr - O ] r.J 2.+.[.V.K.K.K.K.K.K.K.K.K.B.B.B.K.K.K.K.",
"K.K.K.K.K.K./.t.).$.Z b 6 B -XV.K.K.K.K.K.K.K.K.K.K.K.K.B.K.K.K.",
"K.K.K.K.K.K.m.E.m.[.[.M = > !  XB.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.V.K.V.K.K.x.K.^.3 : q.(.S.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.S.K.K.E.^.^.(.S.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.",
"K.K.K.K.K.K.K.K.K.S.K.S.S.S.S.K.S.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K."
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 91 1",
"  c #7E7D7A",
". c #83827F",
"X c #242397",
"o c #0D0DBF",
"O c #1111BE",
"+ c #1C1CB8",
"@ c #2626A7",
"# c #3A3AAD",
"$ c #2C2CBA",
"% c #3232B2",
"& c #3F3EB2",
"* c #454599",
"= c #504F9A",
"- c #696888",
"; c #767488",
": c #706F92",
"> c #4747A9",
", c #4C4BAA",
"< c #605FAA",
"1 c #6867A3",
"2 c #6E6DA7",
"3 c #6F6EAC",
"4 c #0000C4",
"5 c #0D0DC4",
"6 c #0000CC",
"7 c #1111C4",
"8 c #0000DD",
"9 c #0000E1",
"0 c #0000EB",
"q c #0000F4",
"w c #0000FE",
"e c #949382",
"r c #94938E",
"t c #868590",
"y c #8F8E91",
"u c #979592",
"i c #9B9A96",
"p c #9F9D9A",
"a c #A09F9B",
"s c #A3A19E",
"d c #8684AE",
"f c #9B9AA3",
"g c #9493AD",
"h c #8988B1",
"j c #9493B0",
"k c #9C9BB0",
"l c #A6A5A1",
"z c #A9A7A3",
"x c #ABAAA5",
"c c #AEACA9",
"v c #B0AFAB",
"b c #B5B3A5",
"n c #B3B1AC",
"m c #BAB8AF",
"M c #A4A3B3",
"N c #AEACB6",
"B c #B6B5B1",
"V c #B9B7B4",
"C c #BCBAB6",
"Z c #BDBCB9",
"A c #C0BFBB",
"S c #C4C2BD",
"D c #D0CEBE",
"F c #C6C4C1",
"G c #C9C7C2",
"H c #CCCAC5",
"J c #CFCDC9",
"K c #D0CECA",
"L c #D5D3C2",
"P c #D9D7C2",
"I c #DCDAC4",
"U c #D4D2CD",
"Y c #D8D6C9",
"T c #DEDCCF",
"R c #D7D5D0",
"E c #D9D7D3",
"W c #DCDAD5",
"Q c #DEDCD8",
"! c #E1DFC7",
"~ c #E0DED9",
"^ c #E3E1CC",
"/ c #E5E3D5",
"( c #E9E7D3",
") c #EDEBD6",
"_ c #E3E1DC",
"` c #E8E6DB",
"' c #ECE9DA",
"] c #F2F0DE",
"[ c #E6E4E1",
"{ c #E8E6E2",
"} c #EDEAE2",
/* pixels */
"WWWQWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWQWWWWEWEWWWWWWWWQWWWWWWWWWWWWWWWWWW",
"WWWWWQWWWQWWWWWWWEQEWWWWWWWQWWWWWWWWWWWWUWWWQWWW",
"WWQWWWWWWWWWWWWWE`bb`EQWWWWWWWWWWWWWWE_lZ_WWWWWW",
"WWWWWWWWWWWWWWWE`M5+Z~EWWWWWWWWWWWWWE`Bc_EWWWWWW",
"WWWWWWWQWWWQWWWE(,wq1]QEWWWWWWWWWWWW_Fa_WWWWWWWW",
"WWWWWWWWWWWWWWWE/j67txH_QEWWWWWQWWEQKiWWWWWWWWWW",
"WWQWWWWWWWWWWWWWE`sx}FllH_~EEWWWWEWQiJQWWWWWWWWW",
"WWWWWWWWWWWWW~WWE_ZZQQ_GzsG__EEWEE_lA_EWWWWWWWWW",
"WWWWQWWWWWWQWWWWE_CB_EEQ_HxsS~_W`}cn_EWWWWWWWQWW",
"WWWWWWWWWWWWWWWWE_Zm_EWWEQ_JxsSYgpx_WWWWWWWWWWWW",
"WQWWWWWWWWWWWWWWW~Sn_WWWQEE~_Jb*q4N_EWWWWWWWQWWW",
"WWWWQWWWWWW~WWWWW/Sn_EWWEWWEQ[I@q0j`EWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_Fc_WWWWEQ_Kzxf$*v`TWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWQFc`EEEQ`JzsS~`^/zB_EWWWQWWWWWW",
"WWWQWWWWWQWWWWWWW~Gc_E~_HlsS__EEWE_sC_EWWWWWWWWW",
"WWWWWWWWWWWWWWWWEQHx[_GllG__EWWWWWW~pS_EWWWWWWWW",
"WWWWWWWWWWWWQEWWEQUcHslH_~EWWWWWWWWW~pF_EWWWWQWW",
"WWWWWWWWWWWWWWEE__V cH_QEWQEWWWWWEWWWWiH_EWWWWWW",
"WWWWWWWWWEQWEW~~Ssss`WEWWWQWWQWWWWWWE~EuK~EQWWWW",
"WWQWWWWEEQWE/QAaxUExQWWWWWWWWWWWWWWWWE~UuUQEWWWW",
"WWWWWWW_~E_QZsvU__UxQWWWWWWWWWWWWWWWWWW/Hn~WWWQW",
"WWWWWWTcS/VanU_QEQUsQWWWWWWWWWWWWWWWWWWEQQEWWWWW",
"WWWWE/387yCU_WEWWWEs~EWWWWWWWWQWQWWWWWWWTWWW~WWW",
"WWWWE^%w0:TW_~EEWWElWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
"WWWWE/kOXncanGW_~WYlWWWWWWWWWWWWWWWWWWQWWWWWWWWW",
"WWQWWW_Pez{RAxsnGW_xWEWEWWWWWWWWWWWWWWWWWWWWWWWW",
"WWWQWWE_BpB_~_YSxsvuE__WEEWQWWWWWWWWWWWWWWWWWWWW",
"WWWWWWWQABzG~EW~_ES.avSW__WEWWWWWWQWWWQWWWWWWWWW",
"WWWWWWWWElRiWWWWEW_cUFcsxSE__WEWWWWWWWWWWWWWWW~W",
"WWWWWWWE_zJFz_EWWWQlU__WSnszSE_/WEEWWWWWWWWWWWWW",
"WWWWWWWW_Sx}zZ_EWE~zUWEW~_WGvlzAE__WWEWWWWWWWWWW",
"WWWWWWWEWEsQWpUQWW~zUWWWWEW~_WHvszAE_~WEEWWWWWWW",
"WWQWWWWWE_xS~Hs_WE~zKWWWWWWEYW~_WHvszAU__QWWWWWW",
"WWWWQWWWE_Sm}~nn_E_zH~WWWWWWWWWWW~_WHnlzCUWWWWWW",
"WWWWWWWWWQT;kW_sHQ~cHQWWWWWWWWWWWWWW~~~HvC~WWWQW",
"WWWWQWWWE/d98h`JpW~cH~WWWWWWWWWWWWWWWEE~_~EWWWWW",
"WWWWWWWWE'<wq=(}Cl}cF~WEWWWWWWWWWWWWWWWWEWWWWWWW",
"WQWWWWWWEQF#&xsV{xFCGQWWWWWWQWWWWWWWWWWWWWQWWWWW",
"WWQWWWWWWW~^^`EcaAxrn`EWWWWWWWWWWWWWWWWWWWWWWWWW",
"WWWWWQWWWWWWWEQ_Kn-65N_EWQWWQWWW~WWWWWWWWWQWWWWW",
"WWWWWWWWWEQEEWEWQ)>wq2`EWWWWWWWWWWWWWWW~WWWWWWWW",
"WWWWWWWWWWWWWWWWE/MO$V~EWWWWWWWWWWWWWWWWWWWWWWWQ",
"WQWWWQWWWQWWWWWWWW/HL/EWWWWWWWWWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWQWWEQQWWWWWWWWWQWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWWWWEWWWWWWQWWWWWWWWWWWW~WWWWWWQ",
"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWQWWWWWWWWWWWWWWWW"
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
};
const int n_xpm_icons = 3;
