/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"16 16 115 2",
"   c #3333BB",
".  c #706FBA",
"X  c #3838C5",
"o  c #6362C3",
"O  c #6565C3",
"+  c #6E6DC0",
"@  c #8483BB",
"#  c #9D9BB1",
"$  c #9997BC",
"%  c #9E9DBF",
"&  c #B1AFAB",
"*  c #B1AFAD",
"=  c #B4B2AE",
"-  c #B9B8AE",
";  c #A7A5BE",
":  c #B5B3B2",
">  c #BCBAB5",
",  c #BDBBB8",
"<  c #BEBCB8",
"1  c #BFBDB8",
"2  c #BFBDB9",
"3  c #BEBDBA",
"4  c #C1BFBA",
"5  c #C1BFBB",
"6  c #C2C0B2",
"7  c #C1C0BB",
"8  c #C2C0BB",
"9  c #C7C5BA",
"0  c #C7C6BA",
"q  c #C3C1BD",
"w  c #C3C2BD",
"e  c #C2C0BE",
"r  c #C4C2BD",
"t  c #C5C3BE",
"y  c #C6C4BF",
"u  c #C9C7BC",
"i  c #CECDB8",
"p  c #C9C8BE",
"a  c #CDCBBE",
"s  c #D1CFBE",
"d  c #D2D1BD",
"f  c #8382CA",
"g  c #9C9BC8",
"h  c #A3A2C2",
"j  c #A7A5CA",
"k  c #B0AFC8",
"l  c #BDBBC9",
"z  c #C1BFC2",
"x  c #C6C4C0",
"c  c #C6C5C0",
"v  c #C6C4C1",
"b  c #C8C7C0",
"n  c #C8C6C1",
"m  c #C8C6C2",
"M  c #C9C7C2",
"N  c #C9C7C4",
"B  c #CAC8C3",
"V  c #CCCAC4",
"C  c #CCCAC5",
"Z  c #CDCBC6",
"A  c #CDCCC7",
"S  c #CECCC7",
"D  c #C2C1CA",
"F  c #CECCC8",
"G  c #CFCDC8",
"H  c #CECDC9",
"J  c #CDCCCC",
"K  c #D0CEC9",
"L  c #D1CFCA",
"P  c #D0CECB",
"I  c #D4D2C3",
"U  c #D2D0CA",
"Y  c #D2D0CB",
"T  c #D5D3C8",
"R  c #D1D0CC",
"E  c #D2D0CC",
"W  c #D3D1CC",
"Q  c #D2D0CD",
"!  c #D2D1CD",
"~  c #D3D1CD",
"^  c #D2D0CE",
"/  c #D3D1CE",
"(  c #D3D1CF",
")  c #D4D2CD",
"_  c #D5D3CD",
"`  c #D4D2CE",
"'  c #D5D3CE",
"]  c #D4D2CF",
"[  c #D5D3CF",
"{  c #D6D4CE",
"}  c #D6D4CF",
"|  c #D7D5CF",
" . c #D9D7C9",
".. c #D8D6CA",
"X. c #D9D7CE",
"o. c #DEDCCB",
"O. c #DAD8CC",
"+. c #DBD8CC",
"@. c #DAD8CF",
"#. c #DCDACC",
"$. c #DCDACE",
"%. c #DFDDCE",
"&. c #DFDDCF",
"*. c #D6D4D0",
"=. c #D7D5D0",
"-. c #D6D4D1",
";. c #D8D5D0",
":. c #D8D6D1",
">. c #DAD8D3",
",. c #DFDDD0",
"<. c #E0DDCA",
"1. c #E0DECE",
"2. c #E0DED1",
"3. c #E2E0CD",
"4. c #E3E0CD",
/* pixels */
"' ' ' ' ' X.<.' ' ! ' ' ' L ' ' ",
"' ' ' ! 1.g o o.*.' ! -.C q ' ' ",
"' ' ' ! #.k @ 9 x L 2. .> ' ' ' ",
"' ' ' ' { W s :.n u h $  .' ' ' ",
"' ' ' ! ' J q :.*.d . + 1.L *.' ",
"' ' ! ' X.W 8 n < n 2.I 3 :.' ' ",
"W { @.-.L 4 & S ' -.L -.N 4 ' L ",
"{ J l u q n q :.' ' ' ' :.N L *.",
"o.j   4 J ' q :.L ' ' ' ' ' ' ' ",
"W X.& 3 n 4 = C ' -.| ' L ' ' ' ",
"' X.C : Y ' > n 4 q C ' -.:.' ' ",
"! ' L i 9 Y 5 :.' C n 4 q C L ' ",
"' ' @.O % a p ' ' *.*.' G x L ' ",
"' L +.f h - # ' ' L ' ' | X.' ' ",
"' ' ' 1.,.z X z X.' ' ' ' L ' ' ",
"' ' ' L ' :.L W ' ' ' ' ' ' ' ' "
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"32 32 225 2",
"   c #72719C",
".  c #4443AC",
"X  c #4847AE",
"o  c #5E5EA5",
"O  c #6B6AA6",
"+  c #7776A9",
"@  c #6160B9",
"#  c #6564BD",
"$  c #6D6CB9",
"%  c #7877B0",
"&  c #7877B5",
"*  c #0101D2",
"=  c #0505D6",
"-  c #0B0BD2",
";  c #0807D9",
":  c #2020C3",
">  c #2E2EC7",
",  c #0101E5",
"<  c #0000E9",
"1  c #0000F3",
"2  c #0000F6",
"3  c #0000FA",
"4  c #4545C0",
"5  c #4141C5",
"6  c #807FBB",
"7  c #98978B",
"8  c #858491",
"9  c #8E8D9C",
"0  c #959390",
"q  c #9B9A96",
"w  c #9E9C98",
"e  c #B7B69F",
"r  c #9291A5",
"t  c #9C9BAB",
"y  c #8987B9",
"u  c #9190BA",
"i  c #9493BB",
"p  c #A8A6A3",
"a  c #A8A7A3",
"s  c #A9A7A3",
"d  c #A9A7A7",
"f  c #ADACA3",
"g  c #A9A8A5",
"h  c #AAA8A4",
"j  c #ABA9A5",
"k  c #AAA9A6",
"l  c #ACAAA6",
"z  c #ACABA7",
"x  c #ADABA7",
"c  c #ADACA8",
"v  c #AEACA8",
"b  c #AEADA8",
"n  c #AEADA9",
"m  c #AFADA9",
"M  c #AFADAD",
"N  c #B0AFA6",
"B  c #B0AEAA",
"V  c #B0AFAA",
"C  c #B1AFAB",
"Z  c #B2B1A6",
"A  c #B5B3A7",
"S  c #B1B0AB",
"D  c #B6B4AA",
"F  c #B2B0AC",
"G  c #B2B1AC",
"H  c #B2B1AD",
"J  c #B3B1AD",
"K  c #B3B2AD",
"L  c #B1B0AE",
"P  c #B3B1AE",
"I  c #B4B3AE",
"U  c #B5B3AF",
"Y  c #A5A4B2",
"T  c #B6B4B0",
"R  c #B7B5B1",
"E  c #B7B6B1",
"W  c #B7B5B7",
"Q  c #B8B6B2",
"!  c #B8B7B2",
"~  c #B9B7B2",
"^  c #B9B7B3",
"/  c #B9B8B3",
"(  c #BDBBB0",
")  c #BAB8B4",
"_  c #BAB9B4",
"`  c #BBB9B4",
"'  c #BBB9B5",
"]  c #BBBAB5",
"[  c #BCBAB5",
"{  c #BCBAB6",
"}  c #BDBBB7",
"|  c #BAB8BA",
" . c #BDBBB8",
".. c #BEBDB8",
"X. c #BFBDB8",
"o. c #BFBDB9",
"O. c #BFBEB9",
"+. c #BFBDBA",
"@. c #BFBEBA",
"#. c #BBBABF",
"$. c #C0BEAD",
"%. c #C1BFAD",
"&. c #C1BFAF",
"*. c #C1BFB8",
"=. c #C0BEB9",
"-. c #C0BEBA",
";. c #C0BFBA",
":. c #C1BFBA",
">. c #C1BFBB",
",. c #C7C5B0",
"<. c #C2C0B7",
"1. c #C1C0BB",
"2. c #C2C0BB",
"3. c #C4C3BA",
"4. c #C7C5BB",
"5. c #C2C1BC",
"6. c #C3C1BD",
"7. c #C3C2BD",
"8. c #C4C2BD",
"9. c #C4C2BE",
"0. c #C5C3BF",
"q. c #CFCDBB",
"w. c #C6C4C0",
"e. c #C6C5C0",
"r. c #C7C5C2",
"t. c #C8C6C1",
"y. c #C9C7C1",
"u. c #C8C6C2",
"i. c #C9C7C2",
"p. c #C8C7C3",
"a. c #C9C7C3",
"s. c #C9C8C3",
"d. c #CAC8C2",
"f. c #CAC8C4",
"g. c #CBC9C4",
"h. c #CBC9C5",
"j. c #CBC9C7",
"k. c #CCCAC5",
"l. c #CCCAC6",
"z. c #CDCBC6",
"x. c #CDCBC7",
"c. c #CECCC7",
"v. c #CECCC8",
"b. c #CECDC8",
"n. c #CFCDC8",
"m. c #D0CEC9",
"M. c #D1CFC9",
"N. c #D1CFCA",
"B. c #D1CFCC",
"V. c #D1CFCD",
"C. c #D1CFCE",
"Z. c #D8D6C3",
"A. c #D9D7C5",
"S. c #DEDCC6",
"D. c #D2D0CB",
"F. c #D4D2C9",
"G. c #D7D5C8",
"H. c #D6D4CA",
"J. c #D2D0CC",
"K. c #D3D1CC",
"L. c #D2D0CD",
"P. c #D3D1CD",
"I. c #D2D0CE",
"U. c #D3D1CE",
"Y. c #D2D0CF",
"T. c #D3D1CF",
"R. c #D4D2CC",
"E. c #D4D2CD",
"W. c #D5D3CD",
"Q. c #D4D2CE",
"!. c #D4D3CE",
"~. c #D5D3CE",
"^. c #D5D3CF",
"/. c #D6D4CE",
"(. c #D6D4CF",
"). c #D7D4CF",
"_. c #D7D5CF",
"`. c #D9D7C9",
"'. c #D9D7CF",
"]. c #DBD9CA",
"[. c #DBD9CC",
"{. c #DEDCCD",
"}. c #DFDDCF",
"|. c #D4D2D0",
" X c #D5D3D0",
".X c #D5D3D2",
"XX c #D7D5D0",
"oX c #D6D4D1",
"OX c #D6D4D2",
"+X c #D8D5D0",
"@X c #D8D6D0",
"#X c #D9D7D0",
"$X c #D8D6D1",
"%X c #D8D6D2",
"&X c #D9D7D2",
"*X c #D9D7D3",
"=X c #DAD7D2",
"-X c #D9D7D6",
";X c #DAD8D0",
":X c #DBD9D1",
">X c #DAD8D2",
",X c #DBD9D2",
"<X c #DAD8D3",
"1X c #DDDBD0",
"2X c #DEDCD0",
"3X c #DFDDD2",
"4X c #DAD8D4",
"5X c #DBD9D4",
"6X c #DCD9D4",
"7X c #DDDBD6",
"8X c #DEDBD6",
"9X c #DEDCD6",
"0X c #DFDDD8",
"qX c #E0DDC7",
"wX c #E2DFCC",
"eX c #E0DECE",
"rX c #E0DECF",
"tX c #E0DED4",
"yX c #E0DED9",
"uX c #E3E1CD",
"iX c #E3E1CE",
"pX c #E6E4D3",
"aX c #E7E5D3",
"sX c #EDEBD5",
"dX c #E2E0DB",
/* pixels */
"~.~.~.~.~.~.~.~.).K.!.K.K.K.).K.!.oX!.).~.~.~.~.~.K.~.).K.).!.).",
"~.~.~.~.~.~.~.~.!.|.K.<X[.oXK.).).K.).K.~.~.~.~.K.).~.c.).K.).K.",
"~.~.~.~.~.~.~.~.|.K.-X#.  F.K.K.).K.!.!.~.~.K.~.K.4Xc 8.oXK.!.!.",
"~.~.~.~.~.~.~.~.K.|.[.X 3 % aXoXK.K.).K.).K.oXK.4XR ! 4XK.).K.).",
"~.~.~.~.~.~.~.~.K.|.{.y : r D u.*XoXK.K.).~.F.*X7.c <XK.).K.!.).",
"~.~.~.~.~.~.~.~.K.).oXR.A tXu.S c e.<X&XK.B. Xc.a ).!.K.!.).!.!.",
"~.~.~.~.~.~.~.~.~.K.~.F.B ).oX<Xl.S c 8.oXuXS.s b.oXK.).!.).).!.",
"~.~.~.~.~.~.~.~.oXK.~.R.c R.K.K.oX<Xc.K D # X <.4XF.).K.!.K.).!.",
"~.~.~.~.~.~.~.~.~.K.~.~.B ~.~.~.K.K.4XdXf = < | <XK.!.).!.).!.!.",
"~.~.~.~.~.~.~.~.~.~.K.~.B K.K.~.<X).7.h ( u + D 4XK.!.K.).K.K.).",
"~.~.~.~.~.~.~.~.~.K.~.~.c B.<XoXO.f U b.4X2XaXR R 4XK.).K.K.).!.",
"~.~.~.~.~.~.~.K.~.~.K.).T F.1.h R B.<XoXK.K.K.4XK R 4XK.oXF.).!.",
"~.~.~.~.~.~.~.~.K.~.<X'.w a ) K.4X).K.K.).K.K.K.4XV { <XK.).K.!.",
"~.~.~.K.K.K.K.~.&X~.) B q c.4X).K.K.).~.!.!.).K.).<Xc O.<XK.!.).",
"~.~.~.~.3XoX<XK.) h [ oXR b.~.K.oXK.K.).K.).).!.!.!.).z p.oXK.).",
"~.K.~.F.Y f.[ h [ ).4X&XS z.).K.).K.).!.).!.!.K.).F.).).b.).K.!.",
" XB.wX& 2 . ,.-X6X~.B.&XK z.oX~.!.).!.).!.!.).!.K.).K.).).K.).!.",
"~.K.2Xi * o &.C 8.~.&X6XK s.~.~.!.K.).K.).!.K.).!.K.).K.K.!.K.!.",
"~.~.~.{.&.7 z.u.K B K u.K v.6X~.F.K.K.!.K.).!.).).).K.!.K.).).!.",
"~.~.~.~.oXh h &X&X~.e.) 0 s 8.K.<X*X).K.K.K.).K.!.!.).!.).!.!.).",
"~.~.~.B.&X! T C &X~.~.yX! _ ) c K ;.K.oX4X).F.K.K.).K.!.!.).!.).",
"~.~.~.~.&X-.=.! -.&XB.&XR u.3XoXp.! f K O.N.<X<X).K.!.K.!.K.).K.",
"~.~.~.F.~.B.j '.s B.~.&X_ 7.oXK.oX4XoXs.) c S O.b.<X*X).K.).!.!.",
"~.~.~.~.R.&XK R.z.j &X&X) 1.&X~.K.K.).).<XoXl._ c V O.b.).K.K.).",
"~.~.~.K.~.*X-.9 [.! U 0X) 7.&XK.!.K.).K.K.F.oX<X<Xl.{ c c.).K.!.",
"~.~.~.~.B.wX$ 2 @ sXh c.O.| &X~.K.).!.!.K.).!.K.K.).4XoX!.).K.!.",
"~.~.~.~.B.wXy ; O <.l.K 3.3.<X~.).!.).!.!.).).K.).K.F.K.).K.).!.",
"~.~.~.~.~.~.[.q.[.O.c Z 8 t 2XK.K.).K.).!.!.K.).!.).!.K.K.!.!.).",
"~.~.~.~.~.~.K.OXK.4X*XZ - , W <XK.).!.!.!.).K.!.!.).!.!.).).K.).",
"~.~.~.~.K.~.K.~.K.K.|.R.5 > s.oXK.oXK.).!.).).!.!.K.).).!.!.!.!.",
"~.~.~.~.~.~. X~.K.).!.oXA.A.*XF.!.).).!.).K.K.).).K.).K.K.).).K.",
"~.~.~.~.~.~.~.~.!.F.).K.).K.K.).K.K.).!.!.!.).!.!.).!.!.).!.!.)."
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 94 2",
"   c #7A7976",
".  c #7F7E7B",
"X  c #908E7E",
"o  c #222296",
"O  c #0C0CBF",
"+  c #1C1CB7",
"@  c #1110BE",
"#  c #2525A6",
"$  c #3838AC",
"%  c #2B2AB8",
"&  c #3130B1",
"*  c #3D3CB0",
"=  c #454496",
"-  c #404098",
";  c #4E4D98",
":  c #666585",
">  c #6D6C8E",
",  c #727184",
"<  c #4544A7",
"1  c #4A49A8",
"2  c #5D5CA7",
"3  c #6463A0",
"4  c #6B6AA4",
"5  c #6C6BA8",
"6  c #0000C4",
"7  c #0E0EC5",
"8  c #0000CC",
"9  c #1111C1",
"0  c #0000DE",
"q  c #0000E1",
"w  c #0000EB",
"e  c #0000F5",
"r  c #0000FE",
"t  c #82818C",
"y  c #8B898D",
"u  c #908E89",
"i  c #93928E",
"p  c #969591",
"a  c #999794",
"s  c #9C9A96",
"d  c #96949B",
"f  c #9E9C99",
"g  c #A09F9B",
"h  c #A3A29D",
"j  c #A9A79C",
"k  c #AEAD9E",
"l  c #B1B09F",
"z  c #8382AB",
"x  c #8E8DAB",
"c  c #908FAA",
"v  c #9695A1",
"b  c #9594AB",
"n  c #9D9BAD",
"m  c #A6A5A1",
"M  c #A8A7A2",
"N  c #ABAAA5",
"B  c #A5A3A9",
"V  c #A8A7AF",
"C  c #AFADA9",
"Z  c #B0AFAB",
"A  c #B4B2AD",
"S  c #A7A6B0",
"D  c #B6B5B2",
"F  c #B8B7B3",
"G  c #BBB9B5",
"H  c #BEBDB9",
"J  c #C1BFBB",
"K  c #CAC8B7",
"L  c #C4C2BD",
"P  c #CECCBC",
"I  c #D3D2BD",
"U  c #C6C4C0",
"Y  c #C9C7C3",
"T  c #CCCAC5",
"R  c #CFCDC8",
"E  c #D1CFC2",
"W  c #D1CFCB",
"Q  c #D5D3C6",
"!  c #DBDAC3",
"~  c #D5D3CE",
"^  c #D8D6C8",
"/  c #DCDACE",
"(  c #D6D4D0",
")  c #D9D7D1",
"_  c #DCDAD4",
"`  c #DEDCD9",
"'  c #E1DFCB",
"]  c #E1DFD3",
"[  c #E1DEDA",
"{  c #E3E1CC",
"}  c #E8E6CF",
"|  c #E3E1D3",
" . c #EAE8D6",
".. c #E5E3DB",
/* pixels */
"~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ( ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ( ~ ~ ~ ) ~ ( ~ ~ ~ ) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ) ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ( ~ ~ ~ ~ ~ ~ ~ ( ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ R ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ W | k k [ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ _ h G ) ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ) ~ ~ ~ ~ ( ~ ~ ~ W _ n O + D ~ W ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ _ C m _ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ { 1 r e 3  .( ~ ~ ~ ~ ~ ~ ) ~ ~ ~ ~ ~ ~ _ G s _ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ( ~ ~ ~ ~ ~ ~ _ b 8 7 t M U _ ) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ) T i ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ) ~ ~ ~ ~ ~ ~ | f h ..J f h L _ ) ~ ~ ~ ~ ~ ~ ~ ~ ) p Y ) ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ) ~ ~ ~ ~ ~ ~ ~ ~ ~ ) ~ ~ ~ _ F F _ ~ _ L h f J _ ) ~ ~ ~ W W _ f G _ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ _ A A _ ~ R ) _ U h g H _ ~ ~ | ..M N _ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ) F Z _ R ~ ~ ~ ~ _ Y h s H E c d j _ ~ ~ ~ ~ ~ ~ ~ ) ~ ~ ~ ) ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ _ F C _ ~ ~ ~ ~ ~ ~ ~ _ Y C = e 6 V _ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ G C _ ~ ~ ~ ~ ~ ~ ~ ~ [ I # e q b ] ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ) ~ ~ ~ ) ~ ~ ~ ~ _ H N _ ~ ~ ~ ~ ~ _ _ Y h j d % $ k _ ~ ~ ~ ~ ~ ~ ) ~ ~ ~ ~ ) ",
"~ ) ~ ~ ) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ) J N _ R ~ ~ ~ _ U h f H _ _ ! ' h A _ W ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ( L M _ R _ _ U h f L ) ) ~ W ~ ~ ) f F _ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ L m | _ L f f L _ ( ~ ~ ~ ~ ~ ~ ~ ) s G _ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ( T N U f h L _ ( ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ( a J _ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ _ _ A   M U _ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ i L ) ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ _ _ F f s s ` ( ~ ~ ~ ~ ~ ~ ~ ~ ( ~ ~ ~ ~ ~ ~ ~ ~ i Y _ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ _ ~ F s m R ~ h ( ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ T i Y ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ [ _ ~ _ ~ F s M T _ _ T h _ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ _ L C _ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ^ B F ~ A s N W _ ~ ~ ~ R h ~ ~ ~ ~ ~ ( ~ ~ ( ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ) ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ / 5 0 @ y A W _ ~ ~ ~ ~ ~ ~ g ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ( / ~ ",
"~ ~ ~ ~ ~ ! & r w > ^ ) _ ~ ~ ~ ~ ~ R g ~ ~ ~ ~ ~ ~ ~ ( ~ ~ ) ~ ~ ~ ~ ~ ~ ~ ~ ) ~ ~ ~ ( ~ ~ ~ ~ ",
"~ ~ ~ ~ W _ b @ o N m f N L ~ _ ) ~ R g ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ) ~ ~ ~ / I X h [ W G h g N L ~ _ h ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ W _ Z a Z _ ~ _ ~ F m s N i W _ ) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ( ~ ~ ~ ~ ~ ) G Z h J _ ~ ~ ( _ ~ F . s N H ~ _ _ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ f W p ~ ~ ~ ~ ~ ~ _ N R H M f h H ~ _ ) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ) ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ _ h Y H h _ ~ ~ ~ ~ ( f R _ _ ~ H M f h G ~ _ _ ~ ~ ~ ~ ~ ~ ~ ~ ) ~ ~ ~ ~ ~ ~ ~ ",
"~ ( ~ ~ ~ ) ~ ~ _ F M ..h F _ ~ ~ W ) h T ( ~ ~ ) _ ~ H M f m F W _ _ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ~ f ~ ~ p R ( ~ ~ ) h T ( ~ ~ ~ ~ ~ ) _ ~ L N f h F W _ _ ~ ~ W ~ ~ ~ ~ ~ ~ ~ ",
"~ ( ~ ~ ~ ~ ~ ~ ~ _ h L _ L s _ ~ ~ ) h Y ~ ~ ~ ~ ~ ~ ~ ~ ~ _ _ ~ L C f h F R _ ) ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ) F A .._ N C _ W _ m Y ) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ _ _ ( L C f h A W ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ^ , b ^ _ s U ( _ m L ) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ _ ( Y N F _ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ / z q 0 z | T p ~ _ m L ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ) _ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ) ~ ~ ) ~ ~ R | 2 r r ; ' ` F g ..m L ) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ _ H $ * h s F [ m H D L ) W ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ) ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ( ! ! _ R N s F j u C ] ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ) ~ ~ ~ ) ~ ~ ~ ~ ~ W ( ~ ( ` T N : 8 7 V _ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ } < r e 5 { W ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ _ n O + D _ ~ ~ ~ _ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ) ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ / P P _ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ) ~ ~ ~ ~ ~ ~ ",
"~ ~ ) ~ ~ ~ ( ~ ~ ( ~ ~ ~ ~ ~ ~ ~ ~ W ( ( ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ( ~ ~ ~ ~ _ ~ ~ ~ ~ ) ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ",
"~ ~ ~ ~ ~ ~ ( ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ / ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ) "
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
};
const int n_xpm_icons = 3;
